name: Create Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to package (e.g., v1.0.0)'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=tag
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Clone u-root/cpu repository
      run: |
        git clone https://github.com/u-root/cpu.git
        cd cpu
        echo "CPU_VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
    
    - name: Build binaries
      run: |
        cd cpu
        mkdir -p ../binaries
        GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o ../binaries/cpu ./cmds/cpu
        GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o ../binaries/cpud ./cmds/cpud
        chmod +x ../binaries/*
    
    - name: Create Dockerfile
      run: |
        cat > Dockerfile << 'EOF'
        FROM scratch
        COPY binaries/cpu /usr/local/bin/cpu
        COPY binaries/cpud /usr/local/bin/cpud
        COPY BUILD_INFO.txt /BUILD_INFO.txt
        LABEL org.opencontainers.image.title="CPU Binaries"
        LABEL org.opencontainers.image.description="Prebuilt CPU binaries for aarch64"
        LABEL org.opencontainers.image.source="https://github.com/${{ github.repository }}"
        LABEL org.opencontainers.image.version="${{ env.CPU_VERSION }}"
        LABEL org.opencontainers.image.licenses="BSD-3-Clause"
        EOF
    
    - name: Create build info
      run: |
        cat > BUILD_INFO.txt << EOF
        U-Root CPU Binaries for aarch64 (Container Package)
        Built on: $(date -u)
        CPU version: ${{ env.CPU_VERSION }}
        Target architecture: linux/arm64
        Go version: $(go version)
        Container registry: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
        Files in this package:
        - /usr/local/bin/cpu: CPU client binary
        - /usr/local/bin/cpud: CPU daemon binary
        
        Usage:
          docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest /usr/local/bin/cpu -h
          docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest /usr/local/bin/cpud -h
        EOF
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
