name: Create Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to package (e.g., v1.0.0)'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=tag
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Set up Go
      uses: actions/setup-go@v5
    
    - name: Get CPU version for metadata
      run: |
        cd build/repos/cpu
        echo "CPU_VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
    
    - name: Create Dockerfile
      run: |
        cat > Dockerfile << 'EOF'
        FROM scratch
        COPY build/binaries/cpu /usr/local/bin/cpu
        COPY build/binaries/cpud /usr/local/bin/cpud
        COPY build/binaries/identity /etc/identity
        COPY build/binaries/identity.pub /etc/identity.pub
        COPY build/binaries/BUILD_INFO.txt /BUILD_INFO.txt
        COPY build/initramfs/cpud-initramfs.cpio.gz /cpud-initramfs.cpio.gz
        LABEL org.opencontainers.image.title="CPU Binaries"
        LABEL org.opencontainers.image.description="Prebuilt CPU binaries for aarch64 with SSH keys"
        LABEL org.opencontainers.image.source="https://github.com/${{ github.repository }}"
        LABEL org.opencontainers.image.version="${{ env.CPU_VERSION }}"
        LABEL org.opencontainers.image.licenses="BSD-3-Clause"
        EOF
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
